version: "3.9"
services:

  dt2prom:
    build: .
    env_file: .env
    expose:
      - "5000"

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - "./documentation/prometheus_example.yml:/etc/prometheus/prometheus.yml"
